[package]
name = "image_upscale"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fast_image_resize = { version = "5.1.2", features = []}
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "webp"] }
libc = "0.2"
  